### ISSUE TITLE
Example stylesheet adjustments to fix some common issues

### ISSUE THREAD

**Issue by ctrlplusb** [apex/apex-ui-slim#12]
Hey 😃

I have been putting fixes in my custom stylesheet to help with some common problems I have been experiencing.  It helps with #10 and #11 

I thought it worth sharing here.  I will keep updating it as I find more issues/fixes.  Perhaps after a while we could consider patching your plugin with some of these.

```css
/**
 * FIXES FOR APEX-UI-SLIM AND APEX-SYNTAX PLUGINS 
 * Last Updated: 2017/01/23 12:57 UTC+00:00
 */

// Drops the tree-view on left so that the OS X controls aren't overlayed.
atom-panel.tool-panel.panel-left .tree-view-scroller {
  margin-top: 30px;
}

// We dont't want to see the title bar.
atom-panel.panel-header .title-bar {
  visibility: hidden;
}

// Fixes Modals as their widths vary drastically and tend to shift as you
// type input, so preferring a fixed width.
.tree-view-dialog,
.modal.overlay > .select-list {
  width: 80vw;
}

// The highlighted/selected text is too invisible to see.
.command-palette .list-group .character-match {
  color: #000;
}

// Fix the highlighting of items in the tree-view, as the colors change,
// especially with git status it's easier to use an underline to indicate
// the currently selected item.
.tree-view .directory.selected > .header,
.tree-view .list-item.selected {
  color: #212529;
  text-decoration: underline;
}

// Show currently selected item in select lists.
.select-list .list-group li.selected {
  border-left: solid 1px #212529;
}

// We want our wrap guides still. :)
atom-text-editor .wrap-guide, atom-text-editor .wrap-guide {
  background-color: #edecec;
}

// Fixes text highlight on modal popups
.modal atom-text-editor .highlight > .region {
  background: #edecec !important;
}
```

The above works well with the `apex-ui-slim` and `apex-syntax` plugins, along with the atom setting to allow custom titlebars enabled:

<img width="398" alt="screenshot 2017-01-23 09 26 18" src="https://cloud.githubusercontent.com/assets/12164768/22198335/087da620-e14e-11e6-9bc6-85729681caae.png">
