### ISSUE TITLE
gutter and line number improvements

### ISSUE THREAD

**Issue by balupton** [apex/apex-ui-slim#9]
``` less
// ===============================================================
// https://github.com/apex/apex-ui-slim/blob/81f8ac49c0b1632e459a7d04a6febbdb3a39261c/styles/open-color.less#L16-L30

@oc-gray-list: #f8f9fa, #f1f3f5, #e9ecef, #dee2e6, #ced4da, #adb5bd, #868e96, #495057, #343a40, #212529;

@oc-gray-0: extract(@oc-gray-list, 1);
@oc-gray-1: extract(@oc-gray-list, 2);
@oc-gray-2: extract(@oc-gray-list, 3);
@oc-gray-3: extract(@oc-gray-list, 4);
@oc-gray-4: extract(@oc-gray-list, 5);
@oc-gray-5: extract(@oc-gray-list, 6);
@oc-gray-6: extract(@oc-gray-list, 7);
@oc-gray-7: extract(@oc-gray-list, 8);
@oc-gray-8: extract(@oc-gray-list, 9);
@oc-gray-9: extract(@oc-gray-list, 10);

// ===============================================================
// @balupton's things

// needed for the git gutter variables
@import "syntax-variables";

// https://github.com/atom/git-diff/pull/19
atom-workspace.theme-apex-ui-slim atom-text-editor,
atom-text-editor {
	.gutter .line-number {
		&.git-line-modified {
			background: @syntax-color-modified;
			color: white;
		}
		&.git-line-added {
			background: @syntax-color-added;
			color: white;
		}
		&.git-line-removed {
			background: @syntax-color-removed;
			color: white;
		}
	}
}

// apex ui modifications
// https://github.com/apex/apex-ui-slim/issues/9
atom-workspace.theme-apex-ui-slim {
	// fix padding on tab bar
	.tab-bar {
		margin: 0;
	}
	.tree-view-resizer {
		border: 0;
	}

	// line numbers
	atom-text-editor {
		// hide line numbers
		.gutter {
			.line-number {
				opacity: 1;
				transition: color 0.5s cubic-bezier(0.23, 1, 0.32, 1);
				background: @base-background-color;
				color: @base-background-color;
			}
		}

		// show line numbers when gutter hover or selection
		.gutter {
			.line-number.cursor-line:not(.cursor-line-no-selection) {
				color: @oc-gray-5;
			}
			&:hover {
				.line-number {
					color: @oc-gray-4;
				}
				.line-number.cursor-line:not(.cursor-line-no-selection) {
					color:  @oc-gray-7;
				}
			}
		}

		// change modification line numbers to hide/show accordingly
		.gutter .line-number {
			&.git-line-modified {
				color: @syntax-color-modified;
			}
			&.git-line-added {
				color: @syntax-color-added;
			}
			&.git-line-removed {
				color: @syntax-color-removed;
			}
		}
		.gutter .line-number.cursor-line:not(.cursor-line-no-selection),
		.gutter:hover .line-number {
			&.git-line-modified,
			&.git-line-added,
			&.git-line-removed {
				color: white;
			}
		}
	}
}
```

Standard code:

![screen shot 2017-01-17 at 8 51 38 am](https://cloud.githubusercontent.com/assets/61148/22003951/7cc5bc72-dc92-11e6-98c2-ddd3a3675085.png)

Code with changes:

![screen shot 2017-01-17 at 8 53 27 am](https://cloud.githubusercontent.com/assets/61148/22003952/806ddbc0-dc92-11e6-8dfd-7e45ca2f4e31.png)

Code with highlight:

![screen shot 2017-01-17 at 8 53 32 am](https://cloud.githubusercontent.com/assets/61148/22003958/86b6451c-dc92-11e6-8c15-07f72bab2270.png)

Code with highlight and hover on gutter:

![screen shot 2017-01-17 at 8 53 34 am](https://cloud.githubusercontent.com/assets/61148/22003963/928b337a-dc92-11e6-8258-e99a9fe1d7a9.png)

---

from https://github.com/balupton/dotfiles/commit/5af8ede663d5e5e975a7b0646e032e3d9d83aff7 and https://github.com/balupton/dotfiles/blob/5af8ede663d5e5e975a7b0646e032e3d9d83aff7/.atom/styles.less
